# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://www.github.com/lkaupp"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://www.twitter.com/kaupp_me"

[social.params]
icon = "brand-twitter"


[[social]]
identifier = "x"
name = "Research Gate"
url = "https://www.researchgate.net/profile/Lukas_Kaupp"

[social.params]
icon = "fa-researchgate"

[[social]]
identifier = "y"
name = "ORCID"
url = "https://orcid.org/0000-0001-9411-6781"

[social.params]
icon = "fa-orcid"


